version: '3.8'

services:
  postgres:
    build:
      context: ./docker/postgres
    container_name: postgres-messaging
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pg-messaging-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-messaging
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgmessaging.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pg-messaging-network
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-messaging-network:
    driver: bridge